baseURL = "https://dungpmuit.github.io/"
languageCode = "vi-vn"
title = "dungpmuit's blog"
theme = "PaperMod"

[params]
    env = "production"
    description="The space has collected useful knowledge for Cyber Security"
    author="dungpmuit"
    defaultTheme="auto"
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowWordCount = true
    showFullTextContent = false
    ShowTaxonomies = true
    showMeta = true
[params.profileMode]
    enabled = false
    subtitle = "I am a student at University of Information Technology - VNUHCM | Reverse Engineer & Malware Analyst"
    imageUrl = "https://github.com/dungpmuit.png" # Tự động lấy ảnh GitHub của bạn
    imageWidth = 150
    imageHeight = 150
[params.homeInfoParams]
    Title = "dungpmuit's blog"
    Content = "I am a student at **University of Information Technology (UIT)**. <br> Focus: *Reverse Engineering* & *Malware Analysis*."


    [[params.profileMode.buttons]]
        name = "UTCTF"
        url = "posts/utctf"
    [[params.profileMode.buttons]]
        name = "picoCTF"
        url = "posts/picoctf"

[[params.socialIcons]]
    name = "email"
    url = "mailto:dungpm9327@gmail.com"

[[menu.main]]
    name = "🚩 picoCTF"
    url = "posts/picoctf"
    weight = 10
[[menu.main]]
    name = "🚩 UTCTF"
    url = "posts/utctf"
    weight = 20